[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mysql-csv-load"
version = "0.2.0"
description = "Python script to load data from a CSV file into a MySQL database table."
dependencies = [
"mysql-connector-python==9.3.0",
"python-dotenv==1.1.1",
]

[project.scripts]
mysql-csv-load = "mysql_csv_load.main:run"

[tool.setuptools.packages.find]
where = ["src"]
